; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_left
	.word @sfx_ntsc_right

@sfx_ntsc_left:
	.byte $81,$f9,$82,$02,$80,$3f,$89,$f0,$06,$00
@sfx_ntsc_right:
	.byte $81,$7c,$82,$01,$80,$3f,$89,$f0,$06,$00

.export sounds
